# Generated by Django 6.0.7 on 2026-10-02 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price_paise', models.PositiveIntegerField()),
                ('per_user_limit', models.PositiveIntegerField(default=4)),
            ],
            options={
                'db_table': 'tbl_show',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Tbl_Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paise', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('held', 'Held'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='held', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='show.tbl_show')),
            ],
            options={
                'db_table': 'tbl_reservation',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Tbl_Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('held', 'Held'), ('booked', 'Booked')], default='available', max_length=20)),
                ('current_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats_held', to='show.tbl_reservation')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='show.tbl_show')),
            ],
            options={
                'db_table': 'tbl_seat',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Tbl_Reservation_Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_seats', to='show.tbl_reservation')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_seats', to='show.tbl_seat')),
            ],
            options={
                'db_table': 'tbl_reservation_seat',
                'constraints': [models.UniqueConstraint(fields=('reservation', 'seat'), name='uniq_reservation_seat')],
            },
        ),
        migrations.AddConstraint(
            model_name='tbl_seat',
            constraint=models.UniqueConstraint(fields=('show', 'seat_number'), name='uniq_seat_per_show'),
        ),
    ]
