"""
Django settings for bookmyshow project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# loan .env file
from dotenv import load_dotenv
load_dotenv(BASE_DIR / ".env")


def env_bool(name, default):
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


# Deployment-sensitive settings come from the environment.
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/
#
# DEBUG defaults to on for a local `manage.py runserver`; the Docker image sets
# DEBUG=false, so containers (local Compose and the deployed service) run with
# production behaviour - no tracebacks shown to clients.
DEBUG = env_bool('DEBUG', True)

# Required whenever DEBUG is off; the fallback key is only for local runs.
SECRET_KEY = os.environ.get('SECRET_KEY', '')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured('SECRET_KEY must be set when DEBUG is off.')
    SECRET_KEY = 'django-insecure-local-development-only'

# Comma-separated. Defaults cover local runs and `web`, the Compose service
# name, which Prometheus uses as the Host header when scraping.
ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,[::1],web').split(',')
    if h.strip()
]
# On Railway: allow the generated public domain automatically, and the host
# name Railway's health checker sends (https://docs.railway.com/guides/healthchecks).
if os.environ.get('RAILWAY_PUBLIC_DOMAIN'):
    ALLOWED_HOSTS.append(os.environ['RAILWAY_PUBLIC_DOMAIN'])
if os.environ.get('RAILWAY_ENVIRONMENT_NAME'):
    ALLOWED_HOSTS.append('healthcheck.railway.app')

# HTTPS is terminated by the platform's proxy, which forwards plain HTTP and
# says so in X-Forwarded-Proto; trust it so Django knows the request was HTTPS.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
# Admin logins over HTTPS need their origin trusted for CSRF.
CSRF_TRUSTED_ORIGINS = [
    f'https://{h}' for h in ALLOWED_HOSTS
    if h not in ('localhost', '127.0.0.1', '[::1]', 'web', 'healthcheck.railway.app')
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party
    'rest_framework',
    # Local
    'accounts',
    'show',
    'django_prometheus'
]

# Custom user table - see accounts/models/tbl_users.py. This must be set before
# the project's first migration is applied; changing it later requires a
# database reset (see README).
AUTH_USER_MODEL = 'accounts.Tbl_Users'


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/
#
# Authenticate with a JWT and require authentication by default, so a new
# endpoint is protected unless it explicitly opts out. The public auth
# endpoints set ``permission_classes = (AllowAny,)``.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# SimpleJWT
# https://django-rest-framework-simplejwt.readthedocs.io/en/latest/settings.html
# Defaults are a 5 minute access token and a 1 day refresh token.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

# Logging
#
# Everything goes to stdout - `docker compose logs`, and any hosting platform's
# log viewer, pick it up from there. Each request is one JSON line carrying its
# request id (see bookmyshow/log.py and RequestLogMiddleware).
#
#   LOG_FORMAT=json (default) | text   text is easier to read in a local terminal
#   LOG_LEVEL=INFO (default)           level for the app's own `api.*` loggers
LOG_FORMAT = os.environ.get('LOG_FORMAT', 'json')
LOG_LEVEL = os.environ.get('LOG_LEVEL', 'INFO')

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {'()': 'bookmyshow.log.JsonFormatter'},
        'text': {'()': 'bookmyshow.log.TextFormatter'},
    },
    'handlers': {
        'stdout': {
            'class': 'logging.StreamHandler',
            'stream': 'ext://sys.stdout',
            'formatter': LOG_FORMAT,
        },
    },
    'root': {'handlers': ['stdout'], 'level': 'WARNING'},
    'loggers': {
        'api': {'handlers': ['stdout'], 'level': LOG_LEVEL, 'propagate': False},
        'django': {'handlers': ['stdout'], 'level': 'WARNING', 'propagate': False},
        # Django logs every 4xx response here as a warning, which would double
        # each 409 of a burst; the request line already records them. 5xx
        # responses (with their traceback) are still logged at ERROR.
        'django.request': {'handlers': ['stdout'], 'level': 'ERROR', 'propagate': False},
    },
}

MIDDLEWARE = [
    # Outermost: assigns the request id and logs every request once.
    'bookmyshow.middleware.RequestLogMiddleware',
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Innermost, so request.resolver_match is set when it reads the route.
    'bookmyshow.middleware.RequestMetricsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'bookmyshow.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bookmyshow.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# From the DB_* variables: .env for a local run, docker-compose.yml in Docker,
# and on Railway each one references the MySQL service's own variable (see
# README, "Deploy"). docker/entrypoint.sh waits for this same database.
#
# .get rather than [...]: settings are also loaded at image build time
# (collectstatic), where no database is configured. A missing value shows up at
# runtime instead: the entrypoint refuses to start without DB_HOST.

DATABASES = {
    'default': {
        # django-prometheus' wrapper around the MySQL backend: identical
        # behaviour, plus query/connection/error counters on /metrics.
        'ENGINE': 'django_prometheus.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', ''),
        'USER': os.environ.get('DB_USER', ''),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', ''),
        'PORT': os.environ.get('DB_PORT', '3306'),
        # Keep each worker thread's connection open between requests instead
        # of reconnecting every time; health checks drop a dead one first.
        'CONN_MAX_AGE': 60,
        'CONN_HEALTH_CHECKS': True,
        'OPTIONS': {
            # Django's default for MySQL, spelled out because the booking
            # logic depends on it: a locking read sees rows committed by
            # transactions it waited for.
            'isolation_level': 'read committed',
            # Give up on a row lock after 5s (MySQL default: 50s); the
            # reserve/cancel views retry, so a stuck queue fails fast
            # instead of holding a worker thread for 50s.
            'init_command': 'SET SESSION innodb_lock_wait_timeout = 5',
            # PyMySQL upgrades to TLS whenever the server offers it. Inside a
            # private network (Docker Compose, a PaaS internal network) that
            # only costs CPU, so it can be switched off with DB_SSL=false.
            'ssl_disabled': os.environ.get('DB_SSL', 'true').lower() == 'false',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
# `collectstatic` (run in the Dockerfile) gathers the admin's CSS/JS here, and
# WhiteNoise serves it - Django itself only serves static files when DEBUG is on.
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
